#!/usr/bin/env bash
# ==============================================================================
# bootstrap-openclaw-instance.sh
# ------------------------------------------------------------------------------
# Spins up the directory tree and a standalone docker-compose.yml for a single
# named OpenClaw role instance on the VPS. Called as part of the first-time
# deployment flow before deploy-identities.sh.
#
# This does NOT start the container -- it writes files and prints next steps.
# Run it on the VPS itself (or over SSH via connect.sh).
#
# Usage:
#   bootstrap-openclaw-instance.sh <role>        # e.g. ai-eng
#   bootstrap-openclaw-instance.sh <role> --out /tmp/preview   # dry preview
#
# Roles: conductor pm researcher designer backend-eng data-eng ai-eng ui-eng
#        qa-eng devops-eng tech-writer
# ==============================================================================

set -euo pipefail

ROLES=(
  conductor
  pm
  researcher
  designer
  backend-eng
  data-eng
  ai-eng
  ui-eng
  qa-eng
  devops-eng
  tech-writer
)

# Port + tier lookup via case (portable back to bash 3.2, unlike `declare -A`).
# Keep in sync with deploy/docker-compose.yml.
port_for() {
  case "$1" in
    conductor)    echo 47810 ;;
    pm)           echo 47811 ;;
    researcher)   echo 47812 ;;
    designer)     echo 47813 ;;
    backend-eng)  echo 47814 ;;
    data-eng)     echo 47815 ;;
    ai-eng)       echo 47816 ;;
    ui-eng)       echo 47817 ;;
    qa-eng)       echo 47818 ;;
    devops-eng)   echo 47819 ;;
    tech-writer)  echo 47820 ;;
    *) return 1 ;;
  esac
}

tier_for() {
  case "$1" in
    conductor|ai-eng) echo opus ;;
    pm|researcher|designer|backend-eng|data-eng|ui-eng|qa-eng|devops-eng|tech-writer) echo workhorse ;;
    *) return 1 ;;
  esac
}

usage() {
  cat <<EOF
Usage: $(basename "$0") <role> [--out <dir>]

Creates /docker/openclaw-<role>/ with:
  docker-compose.yml   standalone compose file for this role
  .env                 template seeded with AGENT_ROLE + placeholders
  data/                persistent state (bind mount target)

Roles: ${ROLES[*]}

Options:
  --out DIR   Write to DIR instead of /docker/openclaw-<role>/ (useful for testing).
EOF
}

if [[ $# -lt 1 ]]; then
  usage
  exit 2
fi

ROLE="$1"
shift

OUT_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -ge 2 ]] || { echo "error: --out requires argument" >&2; exit 2; }
      OUT_DIR="$2"
      shift 2
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "error: unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

# Validate role.
valid=0
for r in "${ROLES[@]}"; do
  [[ "$r" == "$ROLE" ]] && valid=1
done
[[ "$valid" -eq 1 ]] || { echo "error: role must be one of: ${ROLES[*]}" >&2; exit 2; }

PORT="$(port_for "$ROLE")"
TIER="$(tier_for "$ROLE")"
TARGET="${OUT_DIR:-/docker/openclaw-${ROLE}}"

echo "[bootstrap] role=${ROLE} port=${PORT} tier=${TIER} target=${TARGET}"

mkdir -p "${TARGET}/data"
# The openclaw image creates workspace/ and skills/ inside /data on first boot,
# but seed them so deploy-identities.sh has somewhere to rsync into without
# racing the container's init.
mkdir -p "${TARGET}/data/.openclaw/workspace/corpus"
mkdir -p "${TARGET}/data/.openclaw/skills"

# Slack token env var name mirrors deploy/docker-compose.yml (UPPER_SNAKE of role).
role_upper="$(echo "$ROLE" | tr '[:lower:]-' '[:upper:]_')"
slack_var="SLACK_BOT_TOKEN_${role_upper}"

# --- docker-compose.yml -------------------------------------------------------
# Standalone, self-contained compose file derived from the unified stack's
# openclaw service block. No YAML anchors (they are a unified-file convenience
# -- for a standalone per-role file we just expand the common bits inline).
cat > "${TARGET}/docker-compose.yml" <<EOF
# Standalone docker-compose for openclaw-${ROLE}
# Generated by scripts/bootstrap-openclaw-instance.sh. For the unified
# multi-service stack, see deploy/docker-compose.yml at the repo root.
services:
  openclaw-${ROLE}:
    image: ghcr.io/hostinger/hvps-openclaw:latest
    container_name: openclaw-${ROLE}
    restart: unless-stopped
    mem_limit: 800m
    ports:
      - "${PORT}:8080"
    volumes:
      - ./data:/data
    environment:
      AGENT_ROLE: ${ROLE}
      AGENT_MODEL_TIER: ${TIER}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY}
      OLLAMA_API_KEY: \${OLLAMA_API_KEY}
      OLLAMA_HOST: \${OLLAMA_HOST:-https://ollama.com}
      LANGFUSE_SECRET_KEY: \${LANGFUSE_SECRET_KEY:-}
      LANGFUSE_PUBLIC_KEY: \${LANGFUSE_PUBLIC_KEY:-}
      LANGFUSE_HOST: \${LANGFUSE_HOST:-http://langfuse-web:3000}
      AGENT_MEMORY_DSN: \${AGENT_MEMORY_DSN}
      EMBEDDING_BASE_URL: \${EMBEDDING_BASE_URL:-http://ollama:11434}
      EMBEDDING_MODEL: \${EMBEDDING_MODEL:-nomic-embed-text}
      AGENT_SLACK_BOT_TOKEN: \${${slack_var}:-}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - agent-team_default

networks:
  agent-team_default:
    external: true
    name: agent-team_default
EOF

# --- .env ---------------------------------------------------------------------
# Only written if absent -- don't clobber real secrets on re-run.
if [[ ! -f "${TARGET}/.env" ]]; then
  cat > "${TARGET}/.env" <<EOF
# openclaw-${ROLE} .env -- fill in secrets before \`docker compose up -d\`
AGENT_ROLE=${ROLE}

# LLM access
ANTHROPIC_API_KEY=
OLLAMA_API_KEY=
OLLAMA_HOST=https://ollama.com

# Observability (Langfuse)
LANGFUSE_SECRET_KEY=
LANGFUSE_PUBLIC_KEY=
LANGFUSE_HOST=http://langfuse-web:3000

# Long-term memory (shared postgres on internal network)
AGENT_MEMORY_DSN=

# Slack bot token for this role
${slack_var}=

# Embedding provider (local ollama)
EMBEDDING_BASE_URL=http://ollama:11434
EMBEDDING_MODEL=nomic-embed-text
EOF
  chmod 600 "${TARGET}/.env"
else
  echo "[bootstrap] existing ${TARGET}/.env preserved"
fi

cat <<EOF

[bootstrap] wrote ${TARGET}/
  docker-compose.yml  (standalone, port ${PORT}, tier ${TIER})
  .env                (fill in secrets!)
  data/.openclaw/workspace/corpus/  (target for deploy-identities.sh)
  data/.openclaw/skills/            (target for skills sync)

Next steps (on the VPS):
  1. edit  ${TARGET}/.env   -- paste real secrets for ANTHROPIC_API_KEY,
     OLLAMA_API_KEY, AGENT_MEMORY_DSN, Langfuse keys, Slack token.
  2. cd ${TARGET} && docker compose up -d
  3. From your dev box: ./scripts/deploy-identities.sh --role ${ROLE}

EOF
